name: Make WebAssembly
on:
  push:
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    strategy:
      matrix:
        wasi_sdk_version: [22]

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true

    - name: Downloading wasi-sdk
      run: |
        cd ${{github.workspace}}
        wget --no-verbose https://github.com/WebAssembly/wasi-sdk/releases/download/wasi-sdk-${{matrix.wasi_sdk_version}}/wasi-sdk-${{matrix.wasi_sdk_version}}.0-linux.tar.gz
        tar xf wasi-sdk-${{matrix.wasi_sdk_version}}.0-linux.tar.gz

    - name: Downloading binaryen
      run: |
        cd ${{github.workspace}}
        wget --no-verbose https://github.com/WebAssembly/binaryen/releases/download/version_118/binaryen-version_118-x86_64-linux.tar.gz
        tar xf binaryen-version_118-x86_64-linux.tar.gz

    - name: make
      run: |
        cd ${{github.workspace}}
        make -j$(nproc) WASI_SDK_PATH="${{github.workspace}}/wasi-sdk-${{matrix.wasi_sdk_version}}.0/bin" BINARYEN_PATH="${{github.workspace}}/binaryen-version_118/bin"
        mkdir -p build
        mv *.wasm build/

    - uses: actions/upload-artifact@v4
      with:
        name: build-${{matrix.wasi_sdk_version}}
        path: ${{github.workspace}}/build
        pattern: '*.wasm'
        merge-multiple: true
